### ISSUE TITLE
compile under windows 10 64

### ISSUE THREAD

**Issue by LukyGuyLucky** [thechampagne/webview-c3#1]
I like c3c very much and really excited to find this package.May I ask how to compile the project under Window?Are everthing in the package enough to build,or getting and building webview-c even MS webview stuffs is a must?

More detailed guideline would be much appreciated.

**Comment by thechampagne** [comment]
you need to build [webview](https://github.com/webview/webview) first.
write an example and compile it:
```sh
c3c compile example.c3 webview.c3i -l webview
```
or you can you use [C3 build system](https://c3-lang.org/references/build-system/)

**Comment by LukyGuyLucky** [comment]
Thank you very much for the prompt respond.
